print("##############################")
print("#                            #")
print("#   Favian Triyanda Naufal   #")
print("#        2510817110011       #")
print("#                            #")
print("##############################")